version: 1.0.{build}-{branch}
configuration: Release
branches:
  only:
    - master
    - develop
image: Visual Studio 2017
clone_folder: C:\Projects\Kritikos.Services
clone_depth: 1
environment:
  MSBUILDDISABLENODEREUSE: 1
  GITHUB_REPO_TOKEN:
    secure: Kt8llg7P6qDLTxsELrT4mTcPnY+gNCHw7FrNOyuvQTWdQ774qBosGjZQdf0TDlbp
  SONAR_REPO_TOKEN:
    secure: Bf3wUfAmQNDpzqxcf/7gbDJP6fgz4xnKy8wwoM45N+VxR/FmgOlm1VElFGTrQTf5
  CODECOV_TOKEN:
    secure: +Sz/AmKKNEuZJqjvOWn7jzvyQyjy2ZIzPmELUeN2ulcloND4d60Qs81wD40A8oFt
matrix:
  fast_finish: true
cache:
  - packages -> appveyor.yml
  - C:\Users\appveyor\.sonar\cache -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - git submodule -q update --init
  - dotnet restore --packages packages
before_build:
- ps: >-
    choco install opencover.portable -y --use-system-powershell --no-progress
    choco install codecov -y --use-system-powershell --no-progress
    choco install sonarscanner-msbuild-net46 -y --use-system-powershell --no-progress
    SonarScanner.MSBuild begin /k:"Services" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=akritikos-github" /d:sonar.login=$env:SONAR_REPO_TOKEN
build:
  project: Kritikos.Services.sln
  parallel: true
  verbosity: minimal
after_build:
  - SonarScanner.MSBuild end /d:"sonar.login=$env:SONARCLOUD_TOKEN"
test_script:
- ps: >-
    Remove-Item -Recurse -Force .sonarqube

    SonarQube.Scanner.MSBuild begin /k:"Services" /d:"sonar.organization=akritikos-github" /d:"sonar.host.url=https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="Kritikos.Services.coverage.xml"

    OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test Kritikos.Services.Tests --configuration Debug /p:DebugType=Full"  -output:Kritikos.Services.coverage.xml -oldStyle -excludebyattribute:*.ExcludeFromCodeCoverage*^ -filter:"+[*]* -[Kritikos.Services.Tests*]*" -hideskipped:all

    Push-AppveyorArtifact Kritikos.Services.coverage.xml
after_test:
- ps: >-
    codecov -f MSolve_coverage.xml  -t $env:CODECOV_TOKEN
